import { Geist, Geist_Mono, Signika } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/theme/ThemeProvider";
import { FilterProvider } from "@/context/filterContext";
import { UserProvider } from "@/context/UserContext";

import { ToastContainer, toast } from "react-toastify";
// import ReactECharts from 'echarts-for-react';

import NavBar from "@/layout/NavBar";
import Footer from "@/components/generic/Footer";
import Login from "@/components/user/Login";

const signika = Signika({ subsets: ["latin"], weight: ["400", "700"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${signika.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <FilterProvider>
            <ThemeProvider>
              <NavBar />
              {children}
              <ToastContainer position="top-center" autoClose={5000} />
              {/* // render echarts option. */}
              {/* <ReactECharts option={this.getOption()} /> */}
              <Footer />
            </ThemeProvider>
          </FilterProvider>
        </UserProvider>
      </body>
    </html>
  );
}
